"use client";

import ProgressBar from "@/components/pipeline/ProgressBar";
import LiveTerminal from "@/components/pipeline/LiveTerminal";
import ResultViewer from "@/components/results/ResultViewer";

import { useGeneration } from "@/context/GenerationContext";

export default function DashboardContent() {
  const { jobId, events, loading } = useGeneration();

  return (
    <div className="mt-8 space-y-8">

      {/* Pipeline */}

      <section className="overflow-hidden rounded-2xl border border-white/5 bg-[#111111] shadow-xl">

        <div className="border-b border-white/5 px-7 py-6">

          <h2 className="text-xl font-semibold text-white">

            Pipeline Execution

          </h2>

          <p className="mt-1 text-sm text-zinc-500">

            Live execution progress of your architecture generation.

          </p>

        </div>

        <div className="p-7">

          <ProgressBar />

        </div>

      </section>

      {/* Activity + Results */}

      <div className="grid gap-8 xl:grid-cols-[420px_1fr]">

        {/* Activity */}

        <section className="overflow-hidden rounded-2xl border border-white/5 bg-[#111111] shadow-xl">

          <div className="border-b border-white/5 px-7 py-6">

            <h2 className="text-xl font-semibold text-white">

              Activity

            </h2>

            <p className="mt-1 text-sm text-zinc-500">

              Streaming backend events

            </p>

          </div>

          <div className="p-6">

            <LiveTerminal events={events} />

          </div>

        </section>

        {/* Results */}

        <section className="overflow-hidden rounded-2xl border border-white/5 bg-[#111111] shadow-xl">

          <div className="border-b border-white/5 px-7 py-6">

            <h2 className="text-xl font-semibold text-white">

              Generated Architecture

            </h2>

            <p className="mt-1 text-sm text-zinc-500">

              View every layer generated by the pipeline.

            </p>

          </div>

          <div className="p-7">

            {jobId ? (
              loading ? (
                <div className="flex h-96 items-center justify-center">

                  <div className="text-center">

                    <div className="mx-auto mb-6 h-10 w-10 animate-spin rounded-full border-4 border-zinc-700 border-t-red-600" />

                    <h3 className="text-lg font-semibold text-white">

                      Generating Architecture...

                    </h3>

                    <p className="mt-2 text-sm text-zinc-500">

                      This usually takes a few seconds.

                    </p>

                  </div>

                </div>
              ) : (
                <ResultViewer jobId={jobId} />
              )
            ) : (
              <div className="flex h-96 items-center justify-center">

                <div className="max-w-sm text-center">

                  <div className="mx-auto mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-[#181818]">

                    <svg
                      width="32"
                      height="32"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      className="text-zinc-500"
                    >
                      <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4A2 2 0 0 0 21 16z" />
                    </svg>

                  </div>

                  <h3 className="text-xl font-semibold text-white">

                    No Architecture Yet

                  </h3>

                  <p className="mt-3 text-sm leading-6 text-zinc-500">

                    Enter a prompt above and click
                    <strong className="text-white">
                      {" "}
                      Generate Architecture
                    </strong>
                    . Your generated output will appear here.

                  </p>

                </div>

              </div>
            )}

          </div>

        </section>

      </div>

    </div>
  );
}